apiVersion: ENC[AES256_GCM,data:YFs=,iv:uYSBIdCNwFrPPQktbe+U82VXhT9CIPlTe+NHW8/XdVI=,tag:BUL6s7uJ/JTOi3mJ+Szzgw==,type:str]
kind: ENC[AES256_GCM,data:wSqFGQ2R,iv:FXZxirEuZBFsWyVE2oH3UDAvX4HfExiecYATVDnPgIE=,tag:EomcJJwuSYogjoM0mI8wgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zBFfqzctotTB4EOaW/0=,iv:yrSHuTxz/9H/bmcUMY3ZkhcyoGDKyWGvMmavaibE6Zw=,tag:LiN9T63oqkmf/v3tHEQ1tg==,type:str]
    namespace: ENC[AES256_GCM,data:mcUgGuFY8B7kGuM=,iv:3AMCX70bQ2fF3/qoiydJIROuY1y1BQOp90lYZK7VVzg=,tag:Ua+6FEVQ0gJRDYSQqEVzGw==,type:str]
type: ENC[AES256_GCM,data:DBphiPMGU7LcQzBgOEBoLjNr7wRttNdyi17R/5tD,iv:CjudtSPSXUUPfa4DAa8HmmpKBKoyOycgQJ+lBqC3BF8=,tag:13G9tkBf+BKVgKAkdKBcnA==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:YDnej+Bx8QghHVun5rRgv6oyGEGP6/Tya6k09aLLJoqPZun8l2uPae04pByiwT5o/4nOoTHA1DTdvqqPRzpUbeVPEJnrGpC2DOGGBMHeOqOChikqVr6/RI0De2w4Sr3WkIFD93ynzRZncyTkug0oqa143qXO3wUJQUq0SerZSLFcDO7pJXIu/hSs5J8KSVDGa0UScR9mQ5OkcY79lmKbF8dx7ZTVndsNBWMkwIEX5/joSEau9cYm3bsa2+rjDdDorFLuncKPM0aIrTg6,iv:kg/VzNTi1SNqqak9Z3u/4hzKbj3ZZQnna4SPYkpG40c=,tag:R9aZ/c227oRNKsbMR1FmrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSLzJQVDQvMXZsY0VVN2VX
            VTUrM1RNLzJHckd1UTAxQnlpczZCdWhVbTFVCm9peEtvTU1MQXIwcnl5N0VKaloy
            S3dSRFhHb2MrQzNGdFhsZEdRaXZIcTAKLS0tIElnQ0I0Zmx0UENSSzhLT2t3Q1Zr
            MU9mWGI4UnlJWU0vY2xDWWdxOHF0akEKT3mzWNkOYVj+CKkykANmqDnA0APJLpLj
            lTeXfMhpNSeBxKmQF5KcJF2be+USpU6qv1lPiW2M6CcuKI5g6WMu8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T21:25:52Z"
    mac: ENC[AES256_GCM,data:KCjvhgA1OdUxXTV3oNopNiO8AGDIhwyTEiVrG1uScSNpbWB7P1vqsnC1WbFh1dXijQvsN9TdDvOvbVGrbNp0Ege4YVdEwPFJbpCKviK4sOyHDF+0vJwAKm3KB0ZIc5pvoJtEUv7baQYOMoUfnnoqLth1ud73n+G3GnoF5J1A0Bw=,iv:ED1dvG/XKuJeegxEV/aW1PmVZSwofEkCih+qJVaCRpY=,tag:mGgUC+Ch/b1P7nvOoe7Sww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0-rc.1
