apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tdemo7
    apps.tanzu.vmware.com/workload-type: web
  name: tdemo7
  namespace: default
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  env:
  - name: message
    value: tanzu7
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1
